/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        dark: '#0a0a0a',
        'dark-card': '#111111',
        'dark-border': '#1a1a1a',
        accent: '#FF6B00',
        'accent-dark': '#cc5500',
        grey: '#888888',
        'grey-light': '#aaaaaa',
        win: '#22c55e',
        loss: '#ef4444',
        'upcoming-blue': '#3b82f6',
        gold: '#c9a84c',
        'gold-dark': '#a68a3e',
        'gold-light': '#e0c872',
        brown: '#8b6914',
        'brown-light': '#b8860b',
        'roster-bg': '#0d0d0f',
        'roster-card': '#141416',
        'roster-border': '#2a2520',
        // --- Stitch MCP Config Colors ---
        "surface-container-lowest": "#0a0a0a",
        "on-secondary-container": "#bfb8a9",
        "inverse-on-surface": "#313030",
        "secondary-container": "#4d493d",
        "on-surface-variant": "#d0c5b2",
        "secondary": "#cdc6b6",
        "primary-container": "#c9a84c",
        "primary": "#e6c364",
        "inverse-primary": "#755b00",
        "surface-tint": "#e6c364",
        "surface": "#131313",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#410002",
        "on-tertiary-container": "#86000a",
        "on-error": "#690005",
        "secondary-fixed-dim": "#cdc6b6",
        "on-primary-fixed-variant": "#584400",
        "background": "#0a0a0a",
        "on-secondary": "#343025",
        "surface-container-highest": "#353534",
        "primary-fixed-dim": "#e6c364",
        "on-primary-fixed": "#241a00",
        "surface-bright": "#3a3939",
        "surface-container-high": "#2a2a2a",
        "on-background": "#e8e0d0",
        "on-surface": "#e8e0d0",
        "on-primary-container": "#503d00",
        "inverse-surface": "#e8e0d0",
        "on-primary": "#3d2e00",
        "tertiary": "#ffb4ac",
        "on-tertiary": "#690006",
        "surface-container": "#201f1f",
        "on-secondary-fixed-variant": "#4b463b",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdad6",
        "tertiary-container": "#ff8a7f",
        "primary-fixed": "#ffe08f",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb4ab",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#4d4637",
        "secondary-fixed": "#eae2d2",
        "outline": "#99907e",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#1f1b12",
        "on-tertiary-fixed-variant": "#93000c"
      },
      fontFamily: {
        heading: ['Rajdhani', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        headline: ['Space Grotesk', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      animation: {
        'pulse-live': 'pulse-live 2s ease-in-out infinite',
        'pulse-slow': 'pulse-slow 3s ease-in-out infinite',
        glow: 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        'pulse-live': {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.5 },
        },
        glow: {
          '0%': { boxShadow: '0 0 5px #FF6B00, 0 0 10px #FF6B00' },
          '100%': { boxShadow: '0 0 20px #FF6B00, 0 0 40px #FF6B00' },
        },
      },
    },
  },
  plugins: [],
};
